In [1]:
# fetching the nececssary data from api

In [2]:
# here we used TVMAZE data of movies and fetched the data in jso n format direct from browser

In [10]:
import pandas as pd
import requests

In [32]:
url = "https://api.tvmaze.com/shows"

response = requests.get(url)  # requesting data using url to api, in return we get data

response  # 200 got response , 400 not avaiable , 500 server down

In [24]:
data = response.json() # it explicitly converts incoming data to json format

data

[{'id': 1,
  'url': 'https://www.tvmaze.com/shows/1/under-the-dome',
  'name': 'Under the Dome',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Science-Fiction', 'Thriller'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2013-06-24',
  'ended': '2015-09-10',
  'officialSite': 'http://www.cbs.com/shows/under-the-dome/',
  'schedule': {'time': '22:00', 'days': ['Thursday']},
  'rating': {'average': 6.6},
  'weight': 99,
  'network': {'id': 2,
   'name': 'CBS',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.cbs.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 25988, 'thetvdb': 264492, 'imdb': 'tt1553656'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/610/1525272.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/610/1525272.jpg'},
  'summary': "<p><b>Under the Dome</b> is the story of a small town that is suddenly and inexplicably sealed off from the rest of the world by an enormous transparent dome. The town's inhabitants must deal with surviving the post-apocalyptic conditions while searching for answers about the dome, where it came from and if and when it will go away.</p>",
  'updated': 1769177765,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/1'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/185054',
    'name': 'The Enemy Within'}}},
 {'id': 2,
  'url': 'https://www.tvmaze.com/shows/2/person-of-interest',
  'name': 'Person of Interest',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Action', 'Crime', 'Science-Fiction'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2011-09-22',
  'ended': '2016-06-21',
  'officialSite': 'http://www.cbs.com/shows/person_of_interest/',
  'schedule': {'time': '22:00', 'days': ['Tuesday']},
  'rating': {'average': 8.8},
  'weight': 99,
  'network': {'id': 2,
   'name': 'CBS',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.cbs.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 28376, 'thetvdb': 248742, 'imdb': 'tt1839578'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/163/407679.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/163/407679.jpg'},
  'summary': '<p>You are being watched. The government has a secret system, a machine that spies on you every hour of every day. I know because I built it. I designed the Machine to detect acts of terror but it sees everything. Violent crimes involving ordinary people. People like you. Crimes the government considered "irrelevant". They wouldn\'t act so I decided I would. But I needed a partner. Someone with the skills to intervene. Hunted by the authorities, we work in secret. You\'ll never find us. But victim or perpetrator, if your number is up, we\'ll find you.</p>',
  'updated': 1783133158,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/2'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/659372',
    'name': 'return 0'}}},
 {'id': 3,
  'url': 'https://www.tvmaze.com/shows/3/bitten',
  'name': 'Bitten',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Horror', 'Romance'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2014-01-11',
  'ended': '2016-04-15',
  'officialSite': 'http://bitten.space.ca/',
  'schedule': {'time': '22:00', 'days': ['Friday']},
  'rating': {'average': 7.4},
  'weight': 98,
  'network': {'id': 7,
   'name': 'CTV Sci-Fi Channel',
   'country': {'name': 'Canada', 'code': 'CA', 'timezone': 'America/Toronto'},
   'officialSite': 'https://www.ctv.ca/sci-fi'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 34965, 'thetvdb': 269550, 'imdb': 'tt2365946'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg'},
  'summary': '<p>Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, <b>Bitten</b> follows the adventures of 28-year-old Elena Michaels, the world\'s only female werewolf. An orphan, Elena thought she finally found her "happily ever after" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.</p>',
  'updated': 1704793709,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/3'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/631862',
    'name': 'Truth, Changes, Everything'}}},
 {'id': 4,
  'url': 'https://www.tvmaze.com/shows/4/arrow',
  'name': 'Arrow',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Action', 'Science-Fiction'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2012-10-10',
  'ended': '2020-01-28',
  'officialSite': None,
  'schedule': {'time': '21:00', 'days': ['Tuesday']},
  'rating': {'average': 7.4},
  'weight': 99,
  'network': {'id': 5,
   'name': 'The CW',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.cwtv.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 30715, 'thetvdb': 257655, 'imdb': 'tt2193021'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/143/358967.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/143/358967.jpg'},
  'summary': '<p>After a violent shipwreck, billionaire playboy Oliver Queen was missing and presumed dead for five years before being discovered alive on a remote island in the Pacific. He returned home to Starling City, welcomed by his devoted mother Moira, beloved sister Thea and former flame Laurel Lance. With the aid of his trusted chauffeur/bodyguard John Diggle, the computer-hacking skills of Felicity Smoak and the occasional, reluctant assistance of former police detective, now beat cop, Quentin Lance, Oliver has been waging a one-man war on crime.</p>',
  'updated': 1766868900,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/4'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/1744752',
    'name': 'Fadeout'}}},
 {'id': 5,
  'url': 'https://www.tvmaze.com/shows/5/true-detective',
  'name': 'True Detective',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Crime', 'Thriller'],
  'status': 'Running',
  'runtime': 60,
  'averageRuntime': 63,
  'premiered': '2014-01-12',
  'ended': None,
  'officialSite': 'https://www.max.com/shows/true-detective/9a4a3645-74e0-4e4d-9f35-31464b402357',
  'schedule': {'time': '21:00', 'days': ['Sunday']},
  'rating': {'average': 8.1},
  'weight': 100,
  'network': {'id': 8,
   'name': 'HBO',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.hbo.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 31369, 'thetvdb': 270633, 'imdb': 'tt2356777'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/490/1226764.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/490/1226764.jpg'},
  'summary': '<p>Touch darkness and darkness touches you back. <b>True Detective</b> centers on troubled cops and the investigations that drive them to the edge. Each season features a new cast and a new case.</p><p><i><b>True Detective</b></i> is an American anthology crime drama television series created and written by Nic Pizzolatto.\xa0</p>',
  'updated': 1777231753,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/5'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/2710560',
    'name': 'Night Country: Part 6'}}},
 {'id': 6,
  'url': 'https://www.tvmaze.com/shows/6/the-100',
  'name': 'The 100',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Action', 'Adventure', 'Science-Fiction'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2014-03-19',
  'ended': '2020-09-30',
  'officialSite': None,
  'schedule': {'time': '20:00', 'days': ['Wednesday']},
  'rating': {'average': 7.7},
  'weight': 99,
  'network': {'id': 5,
   'name': 'The CW',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.cwtv.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 34770, 'thetvdb': 268592, 'imdb': 'tt2661044'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/477/1194981.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/477/1194981.jpg'},
  'summary': '<p>Ninety-seven years ago, nuclear Armageddon decimated planet Earth, destroying civilization. The only survivors were the 400 inhabitants of 12 international space stations that were in orbit at the time. Three generations have been born in space, the survivors now number 4,000, and resources are running out on their dying "Ark" - the 12 stations now linked together and repurposed to keep the survivors alive. Draconian measures including capital punishment and population control are the order of the day, as the leaders of the Ark take ruthless steps to ensure their future, including secretly exiling a group of 100 juvenile prisoners to the Earth\'s surface to test whether it\'s habitable.</p>',
  'updated': 1767037139,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/6'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/1913280',
    'name': 'The Last War'}}},
 {'id': 7,
  'url': 'https://www.tvmaze.com/shows/7/homeland',
  'name': 'Homeland',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Thriller', 'Espionage'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2011-10-02',
  'ended': '2020-04-26',
  'officialSite': 'http://www.sho.com/sho/homeland/home',
  'schedule': {'time': '21:00', 'days': ['Sunday']},
  'rating': {'average': 8.2},
  'weight': 95,
  'network': {'id': 9,
   'name': 'Paramount+ with Showtime',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.sho.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 27811, 'thetvdb': 247897, 'imdb': 'tt1796960'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/498/1245275.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/498/1245275.jpg'},
  'summary': '<p>The winner of 6 Emmy Awards including Outstanding Drama Series, <b>Homeland</b> is an edge-of-your-seat sensation. Marine Sergeant Nicholas Brody is both a decorated hero and a serious threat. CIA officer Carrie Mathison is tops in her field despite being bipolar. The delicate dance these two complex characters perform, built on lies, suspicion, and desire, is at the heart of this gripping, emotional thriller in which nothing short of the fate of our nation is at stake.</p>',
  'updated': 1737321678,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/7'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/1801029',
    'name': 'Prisoners of War'}}},
 {'id': 8,
  'url': 'https://www.tvmaze.com/shows/8/glee',
  'name': 'Glee',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Music', 'Romance'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2009-05-19',
  'ended': '2015-03-20',
  'officialSite': 'http://www.fox.com/glee',
  'schedule': {'time': '21:00', 'days': ['Friday']},
  'rating': {'average': 6.7},
  'weight': 97,
  'network': {'id': 4,
   'name': 'FOX',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.fox.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 21704, 'thetvdb': 83610, 'imdb': 'tt1327801'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/0/73.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/0/73.jpg'},
  'summary': '<p><b>Glee </b>is a musical comedy about a group of ambitious and talented young adults in search of strength, acceptance and, ultimately, their voice.</p>',
  'updated': 1781038966,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/8'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/142185',
    'name': 'Dreams Come True'}}},
 {'id': 9,
  'url': 'https://www.tvmaze.com/shows/9/revenge',
  'name': 'Revenge',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Thriller', 'Mystery'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2011-09-21',
  'ended': '2015-05-10',
  'officialSite': None,
  'schedule': {'time': '22:00', 'days': ['Sunday']},
  'rating': {'average': 7.8},
  'weight': 97,
  'network': {'id': 3,
   'name': 'ABC',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://abc.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 28387, 'thetvdb': 248837, 'imdb': 'tt1837642'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/82/206879.jpg'},
  'summary': '<p>This is not a story about forgiveness; <b>Revenge</b> is a show about retribution. Meet Emily Thorne, the newest resident of The Hamptons. When she was a little girl (and known as Amanda Clarke) her father, David Clarke, was framed for a horrific crime and subsequently sent to prison. While serving his time, the conspirators plotted and murdered David in order to prevent the truth from coming out. Emily is now back with a new identity and ready to take vengeance on the people that murdered her father and stole her childhood.</p>',
  'updated': 1766502493,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/9'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/154117',
    'name': 'Two Graves'}}},
 {'id': 10,
  'url': 'https://www.tvmaze.com/shows/10/grimm',
  'name': 'Grimm',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Crime', 'Supernatural'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2011-10-28',
  'ended': '2017-03-31',
  'officialSite': 'http://www.nbc.com/grimm',
  'schedule': {'time': '20:00', 'days': ['Friday']},
  'rating': {'average': 8.4},
  'weight': 99,
  'network': {'id': 1,
   'name': 'NBC',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.nbc.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 28352, 'thetvdb': 248736, 'imdb': 'tt1830617'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/69/174906.jpg'},
  'summary': '<p><b>Grimm </b>is a drama series inspired by the classic Grimm Brothers\' Fairy Tales. After Portland homicide detective Nick Burkhardt discovers he\'s descended from an elite line of criminal profilers known as "Grimms", he increasingly finds his responsibilities as a detective at odds with his new responsibilities as a Grimm.</p>',
  'updated': 1786297847,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/10'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/1009811',
    'name': 'The End'}}},
 {'id': 11,
  'url': 'https://www.tvmaze.com/shows/11/gotham',
  'name': 'Gotham',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Action', 'Crime'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2014-09-22',
  'ended': '2019-04-25',
  'officialSite': 'http://www.fox.com/gotham',
  'schedule': {'time': '20:00', 'days': ['Thursday']},
  'rating': {'average': 7.7},
  'weight': 99,
  'network': {'id': 4,
   'name': 'FOX',
   'country': {'name': 'United States',
    'code': 'US',
    'timezone': 'America/New_York'},
   'officialSite': 'https://www.fox.com/'},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 38049, 'thetvdb': 274431, 'imdb': 'tt3749900'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/189/474715.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/189/474715.jpg'},
  'summary': "<p>The good. The evil. The beginning.</p><p>Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?</p><p><b>Gotham </b>is an origin story of the great DC Comics Super-Villains and vigilantes, revealing an entirely new chapter that has never been told. It follows one cop's rise through a dangerously corrupt city teetering between good and evil, and chronicles the birth of one of the most popular super heroes of our time.</p>",
  'updated': 1764535293,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/11'},
   'previousepisode': {'href': 'https://api.tvmaze.com/episodes/1616387',
    'name': 'The Beginning...'}}},
 {'id': 12,
  'url': 'https://www.tvmaze.com/shows/12/lost-girl',
  'name': 'Lost Girl',
  'type': 'Scripted',
  'language': 'English',
  'genres': ['Drama', 'Fantasy', 'Horror'],
  'status': 'Ended',
  'runtime': 60,
  'averageRuntime': 60,
  'premiered': '2010-09-12',
  'ended': '2015-10-25',
  'officialSite': 'http://www.showcase.ca/lostgirl',
  'schedule': {'time': '22:00', 'days': ['Sunday']},
  'rating': {'average': 7.9},
  'weight': 96,
  'network': {'id': 6,
   'name': 'Showcase',
   'country': {'name': 'Canada', 'code': 'CA', 'timezone': 'America/Toronto'},
   'officialSite': None},
  'webChannel': None,
  'dvdCountry': None,
  'externals': {'tvrage': 26401, 'thetvdb': 182061, 'imdb': 'tt1429449'},
  'image': {'medium': 'https://static.tvmaze.com/uploads/images/medium_portrait/0/137.jpg',
   'original': 'https://static.tvmaze.com/uploads/images/original_untouched/0/137.jpg'},
  'summary': '<p><b>Lost Girl</b> follows supernatural seductress Bo, a Succubus who feeds on the sexual energy of humans. Growing up with human parents, Bo had no reason to believe she was anything other than the girl next door — until she drained her boyfriend to death in their first sexual encounter. Now she has hit the road alone and afraid. <br /> She discovers she is one of the Fae, creatures of legend and folklore, who pass as humans while feeding off them secretly and in different ways, as they have for millennia. Relieved yet horrified to find out that she is not alone, Bo decides to take the middle path between the humans and the Fae while embarking on a personal mission to unlock the secrets of her origin.</p><p>With the help of her human sidekick, Kenzi, and Dyson, a sexy police detective, Bo takes on a challenge every week helping a Fae or human client who comes to her to solve a mystery, or to right a wrong.</p>',
  'updated': 1727612690,
  '_links': {'self': {'href': 'https://api.tvmaze.com/shows/12'},

In [5]:
df = pd.DataFrame(data)  # converting list of dictonaries to dataframe

df.head()

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60,2013-06-24,...,{'average': 6.6},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1769177765,{'self': {'href': 'https://api.tvmaze.com/show...
1,2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60,2011-09-22,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1783133158,{'self': {'href': 'https://api.tvmaze.com/show...
2,3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60,2014-01-11,...,{'average': 7.4},98,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
3,4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60,2012-10-10,...,{'average': 7.4},99,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1766868900,{'self': {'href': 'https://api.tvmaze.com/show...
4,5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63,2014-01-12,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1777231753,{'self': {'href': 'https://api.tvmaze.com/show...

In [6]:
df = df[['id', 'name', 'type', 'language', 'genres', 'status', 'runtime', 'rating', 'premiered']] 
#selecting required columns

df.head()

,id,name,type,language,genres,status,runtime,rating,premiered
0,1,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,{'average': 6.6},2013-06-24
1,2,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,{'average': 8.8},2011-09-22
2,3,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,{'average': 7.4},2014-01-11
3,4,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,{'average': 7.4},2012-10-10
4,5,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,{'average': 8.1},2014-01-12

In [7]:
df.shape

(240, 9)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         240 non-null    int64
 1   name       240 non-null    str
 2   type       240 non-null    str
 3   language   240 non-null    str
 4   genres     240 non-null    object
 5   status     240 non-null    str
 6   runtime    229 non-null    float64
 7   rating     240 non-null    object
 8   premiered  240 non-null    str
dtypes: float64(1), int64(1), object(2), str(5)
memory usage: 26.9+ KB

In [9]:
df.describe()

               id    runtime
count  240.000000  229.00000
mean   125.429167   52.90393
std     72.408268   15.01372
min      1.000000   25.00000
25%     62.750000   30.00000
50%    126.500000   60.00000
75%    188.250000   60.00000
max    249.000000  120.00000

In [25]:
# if having multiple pages

In [29]:

df = pd.DataFrame()

for page in range(5):
    url = f"https://api.tvmaze.com/shows?page={page}"  # looping replacing page number
    
    response = requests.get(url)
    data = response.json()
    
    temp_df = pd.DataFrame(data)
    
    df = pd.concat([df, temp_df], ignore_index=True)  # ignore index maintain continuty of serial

In [30]:
df

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60.0,2013-06-24,...,{'average': 6.6},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1769177765,{'self': {'href': 'https://api.tvmaze.com/show...
1,2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60.0,2011-09-22,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1783133158,{'self': {'href': 'https://api.tvmaze.com/show...
2,3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60.0,2014-01-11,...,{'average': 7.4},98,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
3,4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60.0,2012-10-10,...,{'average': 7.4},99,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1766868900,{'self': {'href': 'https://api.tvmaze.com/show...
4,5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63.0,2014-01-12,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1777231753,{'self': {'href': 'https://api.tvmaze.com/show...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,1245,https://www.tvmaze.com/shows/1245/ironside,Ironside,Scripted,English,"[Drama, Action, Crime]",Ended,60.0,60.0,2013-10-02,...,{'average': 7.7},47,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",None,None,"{'tvrage': 34445, 'thetvdb': 267261, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>In the gritty world of the NYPD, no one's t...",1729264676,{'self': {'href': 'https://api.tvmaze.com/show...
1204,1246,https://www.tvmaze.com/shows/1246/the-jeff-dun...,The Jeff Dunham Show,Reality,English,[Comedy],Ended,30.0,30.0,2009-10-22,...,{'average': 6.6},45,"{'id': 23, 'name': 'Comedy Central', 'country'...",None,None,"{'tvrage': 23468, 'thetvdb': 119761, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p><i><b>""The Jeff Dunham Show""</b></i> is a n...",1704794634,{'self': {'href': 'https://api.tvmaze.com/show...
1205,1247,https://www.tvmaze.com/shows/1247/gooische-vro...,Gooische Vrouwen,Scripted,Dutch,"[Drama, Romance]",Ended,60.0,60.0,2005-10-30,...,{'average': None},42,"{'id': 112, 'name': 'RTL4', 'country': {'name'...",None,None,"{'tvrage': 17089, 'thetvdb': 83010, 'imdb': 't...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Follows four friends in 't Gooi, a Dutch re...",1768284943,{'self': {'href': 'https://api.tvmaze.com/show...
1206,1248,https://www.tvmaze.com/shows/1248/blossom,Blossom,Scripted,English,"[Drama, Comedy, Family]",Ended,30.0,30.0,1990-07-05,...,{'average': 7.5},92,"{'id': 1, 'name': 'NBC', 'country': {'name': '...",None,None,"{'tvrage': 2835, 'thetvdb': 76679, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>The series changed the face of prime-time s...,1704793449,{'self': {'href': 'https://api.tvmaze.com/show...
1207,1249,https://www.tvmaze.com/shows/1249/the-brady-bunch,The Brady Bunch,Scripted,English,"[Comedy, Family]",Ended,30.0,30.0,1969-09-26,...,{'average': 7.3},92,"{'id': 3, 'name': 'ABC', 'country': {'name': '...",None,None,"{'tvrage': 5643, 'thetvdb': 77010, 'imdb': 'tt...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>The Brady Bunch</b> tells the story of C...,1721664754,{'self': {'href': 'https://api.tvmaze.com/show...