In [1]:
import pandas as pd

## Working with JSON

In [2]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
# to import or read api through link
import requests
import pandas as pd

url = "https://api.exchangerate-api.com/v4/latest/INR"

data = requests.get(url).json()

df = pd.DataFrame([data])
df

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
0,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-15,1786752001,"{'INR': 1, 'AED': 0.0384, 'AFN': 0.684, 'ALL':..."

In [4]:
# can use same or similar parameter of csv

## Working with SQL

In [5]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /home/saaho/anaconda3/lib/python3.14/site-packages (2.2.9)

In [6]:
import mysql.connector

In [7]:
# """ conn = mysql.connector.connect(host="localhost", user='root', password='', database= "localDB")"""
# doesnt run in online as db srored locally

' conn = mysql.connector.connect(host="localhost", user=\'root\', password=\'\', database= "localDB")\n'

In [8]:
#  df = pd.read_sql_query("SELECT * FROM localDB", conn)

In [9]:
df

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
0,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-15,1786752001,"{'INR': 1, 'AED': 0.0384, 'AFN': 0.684, 'ALL':..."